services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    image: project_app 
    working_dir: /app
    volumes:
      - .:/app 
    command: ["python", "lang_search.py"]
    container_name: app_container
    depends_on:
      - search_engine 

  search_engine:
    image: searxng/searxng:2024.10.28-b176323e8
    working_dir: /etc/searxng
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml
      - ./uwsgi.ini:/etc/searxng/uwsgi.ini
    ports:
      - "8080:8080"
    command: ["uwsgi", "--ini", "/etc/searxng/uwsgi.ini"]
    container_name: se_container
